### ISSUE TITLE
Create PKGBUILD File

### ISSUE THREAD

**Issue by LinuxPhreak** [LinuxPhreak/username#1]
Create a PKGBUILD file to submit to my Arch Linux repo. Never did it and confused on how to do it

**Comment by JulioJu** [comment]
Hi

I've seen your post on Facebook https://www.facebook.com/groups/linuxperts/permalink/865652776938589/. 

You has forgotten to tag the last commit: https://www.atlassian.com/git/tutorials/inspecting-a-repository/git-tag

Do not forget https://wiki.archlinux.org/index.php/VCS_package_guidelines#Guidelines 

> Suffix pkgname with(…) git. 

It seems has others problems in your `package()` . Actually file `usr/lib/python3.7/site-packages/username/username.py` seems don't exist in the current github repository (check https://github.com/LinuxPhreak/username/tree/master/lib/python3.7/site-packages)

**Comment by LinuxPhreak** [comment]
So your referring to my GIST located here https://gist.github.com/LinuxPhreak/1951bfa7b0b453983f2755de847f93e7

On the repo I added a PKGBUILD that I was able to build using `makepkg -s`

I have not installed it on a system yet but it compiled without errors. The PKGBUILD on the repo can be found here https://github.com/LinuxPhreak/username/blob/master/PKGBUILD

The built version can be installed using pacman after you have added my hosted repo. Info on adding the repo can be found in the README.md file. 

I would be honored if you added my repo and installed some of the software on it. And I would also look forward to hearing back on the results of the installation of username program. 

As for username.py not being in the https://github.com/LinuxPhreak/username/tree/master/lib/python3.7/site-packages location is that going to cause a problem. I would think the main program itself should be in the root. Which is where it currently is stored. If this is not the correct place for it to be stored, I can easily just move it to the correct location.

**Comment by LinuxPhreak** [comment]
> Hi
> 
> I've seen your post on Facebook https://www.facebook.com/groups/linuxperts/permalink/865652776938589/.
> 
> You has forgotten to tag the last commit: https://www.atlassian.com/git/tutorials/inspecting-a-repository/git-tag
> 
> Do not forget https://wiki.archlinux.org/index.php/VCS_package_guidelines#Guidelines
> 
> > Suffix pkgname with(…) git.
> 
> It seems has others problems in your `package()` . Actually file `usr/lib/python3.7/site-packages/username/username.py` seems don't exist in the current github repository (check https://github.com/LinuxPhreak/username/tree/master/lib/python3.7/site-packages)

Also I'm following you. I hope you can return the favor and follow me as well. Thanks again for your advice.

**Comment by JulioJu** [comment]
I seen you has kick off the [pkgver() function](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver()_function), and you has not suffix the name of pkgbuild with `-git` as I've pointed, very bad practice ;-).

**Comment by LinuxPhreak** [comment]
> I seen you has kick off the [pkgver() function](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver()_function), and you has not suffix the name of pkgbuild with `-git` as I've pointed, very bad practice ;-).

Relax buddy I just got on github and saw your post. The PKGBUILD your talking about was made before I saw your post. And I'm currently working on fixing it. No disrespect to you, honestly I'm grateful for your feedback.

**Comment by LinuxPhreak** [comment]
Also I checked out the build and only see the directory usr/lib/python3.7/site-packages in the build. Which I believe means it will place all the files in that directory on a system. I thought it would have put the username.py in the usr/bin directory. I guess I can write a symlink into it in the PKGBUILD file. It appears to be basic shell scripting, with a slight twist. And still reading up on the Arch Linux Packaging Guidelines you shared with me. Thanks your a life saver

**Comment by JulioJu** [comment]
Cool ;-)
